[package]
name = "nautilus-chainlink"
readme = "README.md"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
description = "Chainlink Data Streams integration adapter for the Nautilus trading engine"
categories.workspace = true
keywords.workspace = true
documentation.workspace = true
repository.workspace = true
homepage.workspace = true

[lints]
workspace = true

[lib]
name = "nautilus_chainlink"
crate-type = ["rlib", "cdylib"]

[features]
default = ["live", "high-precision"]
extension-module = [
  "nautilus-core/extension-module",
  "nautilus-model/extension-module",
  "python",
  "pyo3/extension-module",
]
live = ["nautilus-system"]
python = [
  "live",
  "nautilus-core/ffi",
  "nautilus-core/python",
  "nautilus-model/ffi",
  "nautilus-model/python",
  "nautilus-system/python",
  "pyo3",
  "pyo3-stub-gen",
]
high-precision = ["nautilus-model/high-precision"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
nautilus-common = { workspace = true, features = ["live"] }
nautilus-core = { workspace = true }
nautilus-model = { workspace = true }
nautilus-system = { workspace = true, optional = true }

anyhow = { workspace = true }
async-trait = { workspace = true }
bon = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }

chainlink-data-streams-report = "1.0.3"
chainlink-data-streams-sdk = "1.0.3"
hex = "0.4.3"

pyo3 = { workspace = true, optional = true }
pyo3-stub-gen = { workspace = true, optional = true }

[dev-dependencies]
num-bigint = "0.4.6"
rstest = { workspace = true }
